// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package npool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KycManagementClient is the client API for KycManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KycManagementClient interface {
	// Method Version
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type kycManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewKycManagementClient(cc grpc.ClientConnInterface) KycManagementClient {
	return &kycManagementClient{cc}
}

func (c *kycManagementClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/kyc.management.v1.KycManagement/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KycManagementServer is the server API for KycManagement service.
// All implementations must embed UnimplementedKycManagementServer
// for forward compatibility
type KycManagementServer interface {
	// Method Version
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedKycManagementServer()
}

// UnimplementedKycManagementServer must be embedded to have forward compatible implementations.
type UnimplementedKycManagementServer struct {
}

func (UnimplementedKycManagementServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedKycManagementServer) mustEmbedUnimplementedKycManagementServer() {}

// UnsafeKycManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KycManagementServer will
// result in compilation errors.
type UnsafeKycManagementServer interface {
	mustEmbedUnimplementedKycManagementServer()
}

func RegisterKycManagementServer(s grpc.ServiceRegistrar, srv KycManagementServer) {
	s.RegisterService(&KycManagement_ServiceDesc, srv)
}

func _KycManagement_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KycManagementServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kyc.management.v1.KycManagement/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KycManagementServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// KycManagement_ServiceDesc is the grpc.ServiceDesc for KycManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KycManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kyc.management.v1.KycManagement",
	HandlerType: (*KycManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _KycManagement_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/kyc-management.proto",
}
